### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by jonatasbaldin** [CheesecakeLabs/django-drf-boilerplate#11]
We should have a coding style for this project, something that extends PEP8 to our needs.

But not just that, we may have examples with good/bad code on how to create models, views, serializers, permissions, filters and so on.

This would decrease the time when a new developer joins the project AND would be awesome.

What do you think? @CheesecakeLabs/backend 

💃

**Comment by rlander** [comment]
The Django authors provide a [coding style guide](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/) and there's this [document](http://agiliq.com/books/djangodesignpatterns/index.html) that, although old, we could use as a starting point.

**Comment by jonatasbaldin** [comment]
Sorry for the close/open hehehe

I think that's totally a good start! Maybe just put this link on our README?
