### ISSUE TITLE
Pre-commit hook displays wrong line number for partially staged files

### ISSUE THREAD

**Issue by smaniotto** [CheesecakeLabs/django-drf-boilerplate#17]
Code checker routine copies the staged part of a file to a temporary one and runs the verification on this one. Image this scenario, a file has these modifications:
```python
- # this is a number
- number = 1
+ number = 2

   # more code

- # this is a string
- string = 'oi'
+ string = 'olar
```

But only this chunk is staged:
```python
- # this is a string
- string = 'oi'
+ string = 'olar
```

It will raise the code check violation because of the missing closing quote, but will mark it as line 1, and it's actually line 5.

**Comment by jonatasbaldin** [comment]
😢
