### ISSUE TITLE
Implement WSGI for production

### ISSUE THREAD

**Issue by jonatasbaldin** [CheesecakeLabs/django-drf-boilerplate#18]
Sup @CheesecakeLabs/backend!

We need something to run Django in production. gunicorn? uwsgi? anything else?

Let's discuss!

**Comment by joaoricardo000** [comment]
I use gunicorn just because it was the first one I tried and never had to change.

**Comment by smaniotto** [comment]
There's a [benchmark](http://blog.kgriffs.com/2012/12/18/uwsgi-vs-gunicorn-vs-node-benchmarks.html) saying that uWSGI handles much more requests / sec than Gunicorn and a lot of people refer to it. But I found other articles saying it doesn't make much a difference, specially if put behind nginx (didn't save the links sorry).

**Comment by smaniotto** [comment]
PS: another main point to say uWSGI handles more req / sec than Gunicorn, behind nginx, is that nginx implements the uwsgi protocol to talk to uWSGI (server), meanwhile Gunicorn has the overhead of un-/packing HTTP.

**Comment by jonatasbaldin** [comment]
MOAR FEEDBACK 
PLS

**Comment by joaoricardo000** [comment]
Checking the benchmark that @smaniotto pointed, there is no reason to not use uWSGI.

**Comment by jonatasbaldin** [comment]
https://ivan-site.com/2012/09/benchmark-uwsgi-vs-gunicorn-for-async-workers/

http://nichol.as/benchmark-of-python-web-servers
