### ISSUE TITLE
Batteries included-ish

### ISSUE THREAD

**Issue by FrankKair** [CheesecakeLabs/django-drf-boilerplate#30]
There's some tooling that I think that is quite awesome and maybe should be included in all backend projects, such as:

- Django debut toolbar (primarily for performance);
- Watchtower (for AWS Cloudwatch logging);
- Some Pytest / test infrastructure already in place.

Even if it's a small / quick project, we can certainly benefit from the debugging (even for learning purposes!), logging and testing!

**Comment by rlander** [comment]
I agree and I would add a few more:

- werkzeug (better webserver and debugger)
- bpython or ipython (better shell experience)
- bpdb or ipdb (better debbugging)
- django-post-office (simplifies email sending and queueing)
- django-rq (queues)
- django-configuration (class-based settings)
- django-constance (db-based settings)
- django-tables2 (html tables generation, useful for reporting)
- django-filter (easy filters)
- django-reversion (db-backed model history)
- django-import-export(export models as csv)

Maybe we could have a core requirements file and an extended one?

**Comment by FrankKair** [comment]
Nice additions @rlander 👍🏻

Yes, having a `core requirements` and an `extended` one seems like a good approach to me.

Maybe we should also create a small "guide" to show the basic usage of these tools, I don't know, like something to encourage people to use them.
Because we don't want people to think that this is overkill and all.

Let's see what @smaniotto thinks.

😊
