### ISSUE TITLE
Start using dependabot to inform us about libraries upgrades

### ISSUE THREAD

**Issue by rodolfolottin** [CheesecakeLabs/django-drf-boilerplate#55]
A lot of times we've no knowledge about libraries - and its requirements - upgrades. Just when something really critical, [like what happened with Django](https://www.djangoproject.com/weblog/2019/jun/03/security-releases/) on the last year, we start to update our libraries.

And this can create a mess. Since we don't have the habit (for my experience here at Cheesecake, for sure not all are included in this group. But I do 😅 ) of constantly upgrading our libraries, we kinda take the risk of having any API incompatibilities when we have a major version upgrade and it does not guarantee backward compatibility. 

So, to mitigate this risk I thought that we could add [Dependabot](https://dependabot.com/) or any other tool to warn us about outdated dependencies.

What do you guys think? @CheesecakeLabs/backend

**Comment by fredericojordan** [comment]
Isn't dependabot already added? (see #43).

**Comment by rodolfolottin** [comment]
Oh, I didn't see that. But, since we're talking about it...

Is it integrated in all of our projects?

Should it?

**Comment by fredericojordan** [comment]
> Is it integrated in all of our projects?

Oh I see your point.. No, I don't think so!

**Comment by phsetti** [comment]
Great idea, I think this should be in our checklist items. @natamvo what do you think ?

**Comment by fredericojordan** [comment]
We could add a [.dependabot/config.yml](https://dependabot.com/docs/config-file/) file:
```
# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "python"
    directory: "requirements/"
    update_schedule: "live"
```

**Comment by fredericojordan** [comment]
@natamvo So we won't have configuration file? 😢
