### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by jonatasbaldin** [CheesecakeLabs/django-drf-boilerplate#6]
Hi!

Let's use some CI, k? I guess for the first iteration, an unique CI would be just awesome!

- [x] Add configuration for some CI service
- [x] Add information on README.md on how to use it

**Comment by smaniotto** [comment]
I think most projects are using CircleCI, right? They have good integration and a free tier. Sounds like a good start :-)

**Comment by fredericojordan** [comment]
#49

**Comment by fredericojordan** [comment]
#49 has been merged! 😄
